id: AF5E2B82F
title: Prayer for the Long Life of Khandro Tāre Lhamo
type: translation
pechas:
- IBE7424FF
- I462A4402
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:48:05.071956
  last_modified_at: 2023-01-04 12:48:05.071980
  collections:
  - Khandro Tāre Lhamo Series
  - Works of Tibetan Masters
alignment_to_base:
  IBE7424FF/59A7: BDBF
  I462A4402/D634: BDBF
